### ISSUE TITLE
TypeError: Cannot read property 'getAttribute' of undefined (linha 9, arquivo "Código")

### ISSUE THREAD

**Issue by luizbird** [rodrigotm/XMLBMFBOVESPA#1]
Olá.

Primeiramente, obrigado pelo código. Eu tentei rodar aqui e resulta no seguinte erre:
TypeError: Cannot read property 'getAttribute' of undefined (linha 9, arquivo "Código")

**Comment by rodrigotm** [comment]
Opa Luiz! Tudo bem?
Vi que fechou a issue, conseguiu usar o código sem erro?
Você tentou rodar script localmente sem ser pelo Google Script? Se sim, precisaria mudar algumas coisas, pois no código estou utilziando utilitários do próprio Google script que não funcionariam em outro local, a não ser que adapte usando outros métodos. 
Se precisar de alguma ajuda é só pedir
